### PR TITLE
Added web support

### PR DESCRIPTION
**Pull request by roulljdh**
Hello, I initially added web support on this based on the WakeLock API https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

But the API is very young and limited in browser support having been released this year. But I came across a JS Library that not only does support the new API but has support for older/unsupported browsers because it has been developed way before it https://github.com/richtr/NoSleep.js/

So I modified the library and basically wrapped it. I removed the Webpack/CommonJS parts because it wasn't sitting well with Dart's JS interoperability. I also added an `isEnabled` function but that would only be applicable for older browsers that doesn't support the new API because of this next reason

The new APIs are async in nature which means I don't get an immediate response (`WakeLockSentinel`), So if I were to use the `isEnabled` function's return value to check if the `WakeLockSentinel` https://developer.mozilla.org/en-US/docs/Web/API/WakeLockSentinel is null or not then I won't get an updated value on the Dart side of the app. I mean I could modify the JS function with async/await syntax and await that on the Dart code but doing so, I would then break compatibility for older browsers that doesn't support async/await. So I wanted to preserve that backwards compatibility. So what I did was if the browser supports the native API then it would give an immediate boolean response on the `isEnabled` function, So if I were to toggle it on, It would return true. I mean as long the API is supported it would work just fine. It's just not reliable to check if the `WakeLockSentinel` is null immediately without using async/await. I also added some notes on the Dart code, so do check it out

I hope you review and consider adding this

Best regards

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
@roulljdh Thank you so much for this contribution 🔥 This is super amazing 🚀 

1. Do you think you can make the checks pass?
2. Do you think you would be able to use the new federated plugin approach? (see [article](https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6))

Either way, this contribution is very valuable.

**Comment by roulljdh** [comment]
Hello, sorry I'm kind of new to this though so bare with me. I didn't add anything to the Android & iOS side and I did formatted the code recently as well. But still can't solve the tests problem. About the Federated Plugins, I could probably look into that. But I think this approach should suffice for now.

**Comment by roulljdh** [comment]
I ran the tests on my Android phone. All tests has passed.

**Comment by creativecreatorormaybenot** [comment]
@roulljdh I will definitely want to use the federated setup, but I can also set that up - that is no problem. I will take a look at the CI in a second.

**Comment by creativecreatorormaybenot** [comment]
@roulljdh Right, I see. You need to bump the Flutter version in GitHub actions 👍

**Comment by roulljdh** [comment]
Oh. Right. I did built this using the beta build. Where do I set that up?

**Comment by roulljdh** [comment]
Hold on. I think I see it now

**Comment by roulljdh** [comment]
@creativecreatorormaybenot almost, How about for the iPhone tests?

**Comment by creativecreatorormaybenot** [comment]
@roulljdh Nice! Wait, I will adjust it quickly 👍

**Comment by creativecreatorormaybenot** [comment]
@roulljdh Nice that everything passes 🔥 

I will review soon - I can say now that I would not do the package layout like this (changelog, etc.),
i.e. I would do the federated approach instead.

So if there is nothing to change in the review, I will merge the code, but not publish it - then I would
setup the federated structure myself 👍

**Comment by roulljdh** [comment]
@creativecreatorormaybenot Thank you. Looking forward to it. I haven't heard about the federated approach until now. So I'll be sure to check it out once you've done and publish it. This is my third PR so far actually. I didn't expect I'd be able to do this. I'm porting my Flutter app to the web that happens to use this package and I wanted to retain this functionality and I thought that it would be a big help for future devs knowing there's web support for this so I pushed this through and also as a way to give back to the open source community.

**Review by creativecreatorormaybenot — APPROVED** [review]
I think this lgtm 🔥 

Thanks so much again!

I will keep this PR open for the moment being and then use Pigeon + federated plugins to rework the whole plugin (so I will merge the PR when I do that).

Until then, you should be able to use a Git dependency - let me know if a Git dependency works for you; can also publish if it does not, but I would prefer to set up the platform interface first for the published version 👍

I will try to do it this week :)

**Comment by creativecreatorormaybenot** [comment]
Will merge now, but I will not publish the setup like this.

I will restructure the plugin in order to use the federated plugin approach and ideally, I will rewrite the plugin to use `pigeon`, however, I might do that in a later version.

@roulljdh Thank you so much!

**Comment by creativecreatorormaybenot** [comment]
@roulljdh Will be published once #41 is done - hopefully today :)

**Comment by creativecreatorormaybenot** [comment]
@roulljdh I finally published web support 🚀

You can check it out in the repo: https://github.com/creativecreatorormaybenot/wakelock  
Note that I changed the web implementation a bit, but thanks for your contribution nonetheless 💪

The setup is now federated, so the web code lives in the `wakelock_web` package :)

**Comment by roulljdh** [comment]
Ok @creativecreatorormaybenot. I'll check it out. I see you used async await syntax. Was planning to do that as well. But my concern was backwards compatibility. Won't be able to be parsed by older JS engines but that would be ok I guess just add a disclaimer on the package description for the web that it'll support ES8 compliant browsers at the very least.

**Comment by creativecreatorormaybenot** [comment]
@roulljdh If you could rewrite it using `Promise`, that would be awesome 😃
I glanced over `async`/`await`. We could also use a minify tool I suppose, which would also allow to use `class` syntax for NoSleep.

**Pull request merged**
