### PR TITLE
Feature/upgrade dependency constraints

### PR DESCRIPTION
**Pull request by martin-formigas**
Should fix compatibility with the latest version of Flutter/Dart.

### CODE REVIEW

**Comment by martin-formigas** [comment]
@wilfredonoyola well, merging it takes 1 second 😉 I have no clue when some maintainer will find the time to do it though 😉

**Comment by delfme** [comment]
Thx @martin-formigas ! I cannot import it in my pubspec.
Can you see what's the issue here?

Git error. Command: `git clone --mirror https://github.com/formigas/wakelock/tree/feature/upgrade-dependency-constraints.git /Users/delfme/.pub-cache/git/cache/upgrade-dependency-constraints-4f562ec51f22d63e1e299763a005ae2e1e6b48a1`
stdout: 
stderr: Cloning into bare repository '/Users/delfme/.pub-cache/git/cache/upgrade-dependency-constraints-4f562ec51f22d63e1e299763a005ae2e1e6b48a1'...
fatal: repository 'https://github.com/formigas/wakelock/tree/feature/upgrade-dependency-constraints.git/' not found
exit code: 128

**Comment by delfme** [comment]
Nvm I fixed it. thx again

**Comment by delfme** [comment]
However I still get this issue

```
Because wakelock_windows <0.2.1 depends on win32 ^2.0.0 and no versions of wakelock_windows match >0.2.1 <0.3.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
And because every version of wakelock from git depends on wakelock_windows ^0.2.0 and amplify_secure_storage_dart >=0.4.0+1 depends on win32 >=4.1.2 <6.0.0, wakelock from git is incompatible with amplify_secure_storage_dart >=0.4.0+1.
And because amplify_auth_cognito >=1.1.1 depends on amplify_auth_cognito_dart ^0.10.0+1 which depends on amplify_secure_storage_dart ^0.4.0+1, wakelock from git is incompatible with amplify_auth_cognito >=1.1.1.
So, because presence depends on both amplify_auth_cognito 1.1.1 and wakelock from git, version solving failed.
```

Without upgrading wakelock_windows, it is not compatible with AWS amplify plugins, which is much used.

**Comment by martin-formigas** [comment]
@delfme did you override both dependencies?

```yaml
dependency_overrides:
  wakelock_windows:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock_windows/
      ref: main
```

```yaml
dependencies:
  wakelock:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock/
      ref: main
```

**Comment by aytunch** [comment]
@creativecreatorormaybenot could you please look at this PR. It is just version upgrading and will be very helpful.
After this is merged, the community can ask package authors using wakelock in their repos to upgrade to the latest version so please if you have time approve this.

**Comment by delfme** [comment]
> @delfme did you override both dependencies?
> 
> ```yaml
> dependency_overrides:
>   wakelock_windows:
>     git:
>       url: git@github.com:formigas/wakelock.git
>       path: wakelock_windows/
>       ref: main
> ```
> 
>  ```yaml
> dependencies:
>   wakelock:
>     git:
>       url: git@github.com:formigas/wakelock.git
>       path: wakelock/
>       ref: main
> ```

Great! Thx!

**Comment by kostadin24** [comment]
Git error. Command: `git clone --mirror git@github.com:formigas/wakelock.git C:\Users\admin\AppData\Local\Pub\Cache\git\cache\wakelock-53e3cf8b57ecf9bcf486f10f5555e26e8727d47d`
stdout: 
stderr: Cloning into bare repository 'C:\Users\admin\AppData\Local\Pub\Cache\git\cache\wakelock-53e3cf8b57ecf9bcf486f10f5555e26e8727d47d'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
pub get failed
command: "C:\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\admin\AppData\Local\Pub\Cache",
}
exit code: 69

**Comment by mbaz2** [comment]
@martin-formigas solution has worked for me

**Comment by sagnik-sanyal** [comment]
Two of our apps are using AWS libraries and is causing issues. I request the maintainer to merge this PR with the main branch , as it takes very less time to do so.  The package didn't get any update since a year so i think it is high time to do so.

**Comment by miracoli** [comment]
@sagnik-sanyal 
Consider switching to https://pub.dev/packages/wakelock_plus
Published by fluttercommunity.dev

It is a continuation of this project as the owner is not able to work on it at the moment afaik.

**Comment by creativecreatorormaybenot** [comment]
Hi - I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.

**Pull request closed without merging**
