### PR TITLE
Update win32 to support current version (v5)

### PR DESCRIPTION
**Pull request by timsneath**
## Description

Updates win32 to support v5 (or v4, which is source compatible so long as you're not accessing COM APIs, which this code doesn't).

### CODE REVIEW

**Comment by diegotori** [comment]
@creativecreatorormaybenot any progress on this PR, since I'm one of the maintainers of `chewie`, and people are running into this problem due to this.

Furthermore, if you need someone that can review/approve PRs and release new versions, I'm willing to throw my hat into the ring.

Thank you in advance.

**Comment by nilsreichardt** [comment]
Hey @diegotori, unfortunately, @creativecreatorormaybenot is not available for a few months. Therefore, there will be no progress for this package :/

**Comment by nilsreichardt** [comment]
I would highly recommend to override `wakelock_windows` when it's a blocker with:

```yaml
dependency_overrides:
  wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock
      ref: win32-v5
      path: wakelock_windows
```

**Comment by diegotori** [comment]
@nilsreichardt according to his GitHub history, he was active on this repo as of a month ago, commenting that he was going to merge another PR.

Either way @creativecreatorormaybenot, my offer still stands. If you want to add me to this project and to pub.dev (I currently manage releases for both [reorderables](https://pub.dev/packages/reorderables) and [chewie](https://pub.dev/packages/chewie), you can add me at diegotoridoesandroid@gmail.com.

You don't have to do this alone if folks like myself are willing to lend their time for this.

**Comment by nilsreichardt** [comment]
@diegotori Yes, that true. I was in personal touch to talk to him. The only thing I can say is that I don't think this PR will be merged in the next months. Therefore, I recommend using the override to git reference.

**Comment by timsneath** [comment]
Diego, let's assume that there are some factors that prevent him from being active here for now and that Nils is representing him well when he says that it's not possible to contribute for the time being. 

But that's also the beauty of open source; it's fine to temporarily fork to move forward, since the licenses are permissive. Maybe for now you might want to create `wakelock2` to workaround this and get updates published; if and when normal service is resumed, it's easy enough to revert back to the main `wakelock` and archive/discontinue `wakelock2`. WDYT?

**Comment by diegotori** [comment]
> Diego, let's assume that there are some factors that prevent him from being active here for now and that Nils is representing him well when he says that it's not possible to contribute for the time being.
> 
> But that's also the beauty of open source; it's fine to temporarily fork to move forward, since the licenses are permissive. Maybe for now you might want to create `wakelock2` to workaround this and get updates published; if and when normal service is resumed, it's easy enough to revert back to the main `wakelock` and archive/discontinue `wakelock2`. WDYT?

I would end up doing that with the blessing of the original author. Even then, `wakelock` was merely a continuation of another library called `screen` that has long been abandoned.

I need to run this by the primary maintainers of the `fluttercommunity` GitHub project, so that it can be added there and controlled from there so that it has a more permanent home.

**Comment by diegotori** [comment]
@timsneath https://github.com/fluttercommunity/community/issues/123. Filed a proposal for @fluttercommunity to possibly take over this plugin, assuming @creativecreatorormaybenot approves this action.

If that doesn't work out, then I'll take the mantle of creating it as a new separate project under @fluttercommunity (i.e. `wakelock2`).

**Comment by diegotori** [comment]
@nilsreichardt if you're in constant contact with him, please bring this to his attention. Thanks in advance.

**Comment by nilsreichardt** [comment]
> If that doesn't work out, then I'll take the mantle of creating it as a new separate project under https://github.com/fluttercommunity (i.e. wakelock2).

I would recommend taking directly this way.

**Comment by aalex** [comment]
For now, I am using @timsneath 's fork directly from the git repo.

Please let us know here when a fork as been created and published.

```
dependency_overrides:
  wakelock:
    git:
      url: https://github.com/timsneath/wakelock.git # repository
      ref: win32-v5 # branch
      path: wakelock/ # folder
  wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock.git # repository
      ref: win32-v5 # branch
      path: wakelock_windows/ # folder
```

**Comment by nilsreichardt** [comment]
@aalex I think it should also work when only override `wakelock_windows`:

```yaml
dependency_overrides:
  wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock
      ref: win32-v5
      path: wakelock_windows
```

As shown here: https://github.com/creativecreatorormaybenot/wakelock/pull/203#issuecomment-1547800968

**Comment by diegotori** [comment]
@timsneath if I'm able to create a new repo to host this one, would you be able to resubmit your PR there? Currently reached out to the heads of [@fluttercommunity](https://github.com/fluttercommunity) in order to make this happen.

**Comment by timsneath** [comment]
Yeah, or you can just update it directly in the fork...?

**Comment by slightfoot** [comment]
I've reached out to @creativecreatorormaybenot on a few other channels and hopefully we can get this PR reviewed and merged.

**Comment by diegotori** [comment]
> I've reached out to @creativecreatorormaybenot on a few other channels and hopefully we can get this PR reviewed and merged.

@slightfoot any progress on this, since it's coming up on three weeks now.

At this point, you may want to consider creating a repo within the @fluttercommunity project in order to host this going forward. Unless we have confirmation that @creativecreatorormaybenot is still actively supporting this project, we may need to consider the worst case and start moving on from this repo and hosting it from the @fluttercommunity end, and as I stated before, I'm willing to lend my time in maintaining the project, especially clearing up the PR backlog.

Right now, chewie, a project that I'm currently a maintainer of, is hard-blocked by this PR. Ideally, I would want to continue using this plugin, but I also have to prepare for the worst case and consider the possibility that the maintainer simply does not have the time to dedicate to this project, let alone assign anyone to relive him of that responsibility.

@slightfoot please reach out to him one more time. If you don't hear from him within the next couple of days, then we have to presume that this plugin is abandoned and we must consider migrating a fork of it to @fluttercommunity, where it can be maintained by folks such as myself.

Thank you in advance.

**Comment by nilsreichardt** [comment]
> Unless we have confirmation that @creativecreatorormaybenot is still actively supporting this project, we may need to consider the worst case and start moving on from this repo and hosting it from the https://github.com/fluttercommunity end, and as I stated before, I'm willing to lend my time in maintaining the project, especially clearing up the PR backlog.

As I already suggested, you shouldn't wait on @creativecreatorormaybenot and directly start with a fork because @creativecreatorormaybenot isn't available for the next months.

**Comment by diegotori** [comment]
> > Unless we have confirmation that @creativecreatorormaybenot is still actively supporting this project, we may need to consider the worst case and start moving on from this repo and hosting it from the https://github.com/fluttercommunity end, and as I stated before, I'm willing to lend my time in maintaining the project, especially clearing up the PR backlog.
> 
> As I already suggested, you shouldn't wait on @creativecreatorormaybenot and directly start with a fork because @creativecreatorormaybenot isn't available for the next months.

@slightfoot see the above. I think it's time that we create a fork of this project within @fluttercommunity.

I should still have my pub.dev access for your org (that's how I'm able to publish updates for `chewie`), so this should be doable very quickly and within the next couple of days, or even tonight.

@slightfoot It's your call at this point.

**Comment by archsmilson** [comment]
Any progress here? It seems only reasonable to me to continue the project under the fluttercommunity banner. Considering this package only has a single maintainer who is absent.

**Comment by albertmoravec** [comment]
Hi @diegotori, I got kinda lost at the current progress. Do you plan on maintaining your own fork (https://github.com/diegotori/wakelock) for now and then possibly transfer the package to flutter community?

**Comment by diegotori** [comment]
> Hi @diegotori, I got kinda lost at current progress. Do you plan on maintaining your own fork (https://github.com/diegotori/wakelock) for now and then possibly transfer the package to flutter community?

That's the current plan.

Right now, I'm almost done syncing up my fork of this library with the pending PRs, including this one.

Once that's done, then the plan is to create a repo with a renamed version of my fork of this library (let's call it `wakelock_plus`) and then transfer it to the Flutter Community GitHub repo.

@slightfoot has already given the OK for this on Slack, but I just have to get to that point very soon.

**Comment by chandrabezzo** [comment]
Hi @diegotori thanks for your support about this issue. Can you give us estimation or maybe you can publish to fix this issue because many people need this dependency at Flutter 3.10. For anyone use @timsneath repo like me you all can use my repo for temporary fix.

```
  wakelock:
    git:
      url: https://github.com/chandrabezzo/wakelock.git # repository
      ref: main # branch
      path: wakelock/ # folder
  wakelock_windows:
    git:
      url: https://github.com/chandrabezzo/wakelock.git # repository
      ref: main # branch
      path: wakelock_windows/ # folder
```

**Comment by uzuki-P** [comment]
[Wakelock Plus](https://pub.dev/packages/wakelock_plus) is published on pub.dev

**Pull request closed without merging**
