### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by jpnurmi**
## Description

Implements Linux support (#97) using [dbus](https://pub.dev/packages/dbus) and [org.freedesktop.ScreenSaver](https://specifications.freedesktop.org/idle-inhibit-spec/latest/re01.html).

### CODE REVIEW

**Comment by Kazade** [comment]
It would be really cool if this got merged - is there something in particular holding it up?

**Comment by Areopagitics** [comment]
looking forward to it

**Comment by jhonatan-3a** [comment]
Consider switching to https://pub.dev/packages/wakelock_plus
Published by fluttercommunity.dev

It is a continuation of this project as the owner is not able to work on it at the moment afaik.

**Comment by creativecreatorormaybenot** [comment]
Hi - I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.

**Pull request closed without merging**
