### PR TITLE
fix: Avoid changes in values unexpected

### PR DESCRIPTION
**Pull request by KiritoBeater**
## Description

[Fix issues 63](https://github.com/creativecreatorormaybenot/wakelock/issues/63#issue-753441324)

User KVO to fix: Avoid changes in `UIApplication.sharedApplication.idleTimerDisabled` unexpected.

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
Fixes #63.

**Comment by creativecreatorormaybenot** [comment]
Will review in a bit - thanks for contributing! 😄

**Comment by KiritoBeater** [comment]
thank you😏

**Comment by creativecreatorormaybenot** [comment]
@KiritoBeater Could you _describe_ the change and how it works?

Do you have a link to a resource explaining that the proposed change is the correct way?

The [StackOverflow answer you linked in #63](https://stackoverflow.com/a/23692558/6509751) does something different.

**Comment by KiritoBeater** [comment]
I use [KVO](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html) to make the plugin instance observe `UIApplication.sharedApplication.idleTimerDisabled`'s value change.

```objective-c
[UIApplication.sharedApplication addObserver:instance forKeyPath:@"idleTimerDisabled" options:NSKeyValueObservingOptionNew context:mKeyPathObserverContextApplicationIsIdleTimerDisabled];
```

When `UIApplication.sharedApplication.idleTimerDisabled` is changed , it will call 
```objective-c
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
``` 
Then, in the method, I correct the `UIApplication.sharedApplication.idleTimerDisabled` value to the value I used to set.
```objective-c
- (void)toggle:(FLTToggleMessage*)input error:(FlutterError**)error {
  NSNumber *enable = input.enable;
 +  self.enable = enable.boolValue;
  NSNumber *enabled = [NSNumber numberWithBool:[[UIApplication sharedApplication] isIdleTimerDisabled]];
  
  if (![enable isEqualToNumber:enabled]) {
    [[UIApplication sharedApplication] setIdleTimerDisabled:enable.boolValue];
  }
}
```
Finally, I remove the observe event in the method `dealloc` that call when the plugin instance dealloc. 
```objective-c
- (void)dealloc {
  [UIApplication.sharedApplication removeObserver:self forKeyPath:@"idleTimerDisabled" context:mKeyPathObserverContextApplicationIsIdleTimerDisabled];
}
```
I think the the plugin instance will dealloc when the `flutter engines` dealloc, but I couldn't confirm it. It's only a code habit.

I don't have a link to a resource explaining that the proposed change is the correct way and I don't confirm that it's the best way, but I used it all the time, and no problem. And it resolve my problem now. YES, The problem is serious for me.

**Comment by creativecreatorormaybenot** [comment]
@KiritoBeater Thanks! I see now :)

**Review by creativecreatorormaybenot — APPROVED** [review]
LGTM thanks

I will try to see if I can fix the integration test check.

**Comment by creativecreatorormaybenot** [comment]
@KiritoBeater One last question: are you already using null safety?

I will publish it to the prerelease anyway, but if you are not using null safety, I also need to publish it to the release :)

**Comment by KiritoBeater** [comment]
No，I'm not using null safety. Because the Flutter after 1.20 have a serious bug forme at the platform view. And I am using the Flutter version 1.17.5.

I am using the code that load from my repo in our project.

**Comment by creativecreatorormaybenot** [comment]
@KiritoBeater So would you be fine if I did not publish a new non-null-safety version for this?

You would have to use your custom fork then.

**Comment by KiritoBeater** [comment]
Yes，I will be fine.Thank you. You are very nice.

**Comment by creativecreatorormaybenot** [comment]
Cannot get the integration tests to run successfully for whatever reason (see https://github.com/flutter/flutter/issues/71515).

Tested the example app on a simulator and it seems to work fine.

**Pull request merged**
