### PR TITLE
Updated win32 to ^4.1.3 

### PR DESCRIPTION
**Pull request by fikretonuresen**
Trying to fix issue #194 

Updated win32 to ^4.1.3 and flutter_lints to ^2.0.1

### CODE REVIEW

**Review by creativecreatorormaybenot — APPROVED** [review]
LGTM

Thanks for you contribution!

**Comment by MrCsabaToth** [comment]
This is needed.
"And because file_picker >=5.2.11 depends on win32 ^4.1.3, wakelock ^0.6.2 is incompatible with file_picker >=5.2.11."

**Comment by asaarnak** [comment]
@creativecreatorormaybenot 
Waiting for this to be merged to fix this also.
`And because share_plus >=7.0.0 depends on win32 ^4.0.0, wakelock ^0.6.2 is incompatible with share_plus >=7.0.0.`

**Comment by provokateurin** [comment]
@fikretonuresen You need to bump the minimum dart sdk version to make CI happy.

**Comment by OutdatedGuy** [comment]
@creativecreatorormaybenot, Yo, when are you planning to merge this PR?

**Comment by fikretonuresen** [comment]
> @fikretonuresen You need to bump the minimum dart sdk version to make CI happy.

bumped it and made a commit

**Comment by AndreHaueisen** [comment]
Is this good to go?

**Comment by jhonatan-3a** [comment]
i dream every night about this PR

**Comment by jhonatan-3a** [comment]
i been having soo many problems with the fork of this package i made, just for this update

**Comment by provokateurin** [comment]
@creativecreatorormaybenot Hi, would it be possible to get this merged and released? Currently the package is broken for many people because of this. I hope you aren't having personal troubles or lost interest in this repository

**Comment by alexmercerind** [comment]
> I dream every night about this PR

I share the same dream.

**Comment by jhonatan-3a** [comment]
Consider switching to https://pub.dev/packages/wakelock_plus
Published by fluttercommunity.dev

It is a continuation of this project as the owner is not able to work on it at the moment afaik.

**Pull request closed without merging**
